name: 'databricks_dbt_f1'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks_dbt_f1'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  databricks_dbt_f1:
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
